"""agentorch init - initialize a repository for use with agentorch."""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

# Source of default user configs (bundled with the package)
_PKG_CONFIGS_USER = Path(__file__).resolve().parents[1] / "configs" / "user"

_GITIGNORE_BLOCK = """
# agentorch-ctx generated data
.agentorch/artifacts/
.agentorch/facts/probe-results/
.agentorch/state/
"""

_WRAPPER_CONTENT = """\
#!/usr/bin/env bash
# agentorch-run - thin wrapper that delegates to the globally installed agentorch CLI.
# Generated by `agentorch init`. Safe to commit.
set -euo pipefail
exec agentorch "$@"
"""


def run(target_dir: Path | None = None, *, force: bool = False) -> int:
    """
    Initialize a repository at `target_dir` (default: current working directory).
    Creates .agentorch/configs/, .agentorch/artifacts/, agentorch-run wrapper,
    and updates .gitignore.
    Returns 0 on success, 1 on error.
    """
    repo_root = (target_dir or Path.cwd()).resolve()
    agentorch_dir = repo_root / ".agentorch"
    configs_dir = agentorch_dir / "configs"
    artifacts_dir = agentorch_dir / "artifacts"
    state_dir = agentorch_dir / "state"

    # --- Legacy collab/ detection ---
    legacy_collab = repo_root / "collab"
    if legacy_collab.is_dir() and (legacy_collab / "configs").exists():
        print("  [info] Detected legacy 'collab/' directory.")
        print(
            "  [info] Run 'agentorch migrate' to migrate existing data to .agentorch/."
        )
        print()

    # --- Create directories ---
    configs_dir.mkdir(parents=True, exist_ok=True)
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    state_dir.mkdir(parents=True, exist_ok=True)

    # --- Copy default user configs (skip if already present, unless --force) ---
    config_files = [
        "providers.json",
        "plan.json",
        "impl.json",
        "review.json",
        "harden.json",
    ]
    for filename in config_files:
        src = _PKG_CONFIGS_USER / filename
        dst = configs_dir / filename
        if dst.exists() and not force:
            print(
                f"  [skip] {dst.relative_to(repo_root)} (already exists; use --force to overwrite)"
            )
        else:
            if src.exists():
                shutil.copy2(src, dst)
                print(f"  [ok]   {dst.relative_to(repo_root)}")
            else:
                print(f"  [warn] source config not found: {src}", file=sys.stderr)

    # --- Write .agentorch/.gitignore ---
    inner_gi = agentorch_dir / ".gitignore"
    if not inner_gi.exists() or force:
        inner_gi.write_text("artifacts/\nfacts/probe-results/\nstate/\n", encoding="utf-8")
        print(f"  [ok]   {inner_gi.relative_to(repo_root)}")

    # --- Update repo root .gitignore ---
    root_gi = repo_root / ".gitignore"
    existing = root_gi.read_text(encoding="utf-8") if root_gi.exists() else ""
    if ".agentorch/artifacts/" not in existing:
        with root_gi.open("a", encoding="utf-8") as handle:
            handle.write(_GITIGNORE_BLOCK)
        print("  [ok]   .gitignore (appended agentorch data entries)")

    # --- Write agentorch-run wrapper ---
    wrapper = repo_root / "agentorch-run"
    if not wrapper.exists() or force:
        wrapper.write_text(_WRAPPER_CONTENT, encoding="utf-8")
        wrapper.chmod(0o755)
        print("  [ok]   agentorch-run (wrapper script)")
    else:
        print("  [skip] agentorch-run (already exists; use --force to overwrite)")

    print()
    print("Repository initialized for agentorch.")
    print(f"  configs : {configs_dir.relative_to(repo_root)}")
    print(f"  artifacts: {artifacts_dir.relative_to(repo_root)}")
    print()
    print("Next: edit .agentorch/configs/providers.json to set your preferred models.")
    return 0
